### ISSUE TITLE
Going to localhost:9000 returns Action Not Found

### ISSUE THREAD

**Issue by iabouhashish** [yohangz/java-play-react-seed#2]
I cloned the repo, localhost:3000 works exactly as intended. But trying to access Play Framework at localhost:9000 returns an Action Not Found Error, the console gives me a 404 Not Found Error.

**Comment by yohangz** [comment]
@iabouhashish , it is the expected behavior. In development mode you have to use localhost:3000 and localhost:9000 will serve only play backend which will be proxied via localhost:3000.

Unified workflow will work once you build the project and run it with the desire port. Please read [this](http://bit.ly/2A1AzEq) blogpost for additional information.
